### ISSUE TITLE
The ValidateTaxNumberOut does not match output schema in api document

### ISSUE THREAD

**Issue by dy93** [taxamo/taxamo-python#3]
according to [GET /api/v1/tax/vat_numbers/{tax_number}/validate](https://api.taxamo.com/swagger/ui/index.html#!/tax/validateTaxNumber) 

the **ValidateTaxNumberOut** should have a schema like this:
```
{
  "tax_deducted": false,
  "buyer_tax_number": "",
  "buyer_tax_number_normalized": "",
  "buyer_tax_number_valid": false,
  "buyer_tax_number_format_valid": false,
  "billing_country_code": ""
}
```
but actually the *buyer_tax_number_format_valid* field was lost in **ValidateTaxNumberOut** class

maybe this module is out-dated and you should re-generate it from swagger file again?

**Comment by tlipski** [comment]
updated bindings, please see if it helps
